version: '3'

services:
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        networks:
            - nlp-net
        restart: always
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    master:
        image: lachrimae/hadoop-master
        container_name: master
        expose: 
            - "5432"
            - "20"
        networks:
            - nlp-net
        depends_on:
            - db
            - slave
    slave:
        image: lachrimae/hadoop-slave
        container_name: slave
        expose:
            - "20"
        networks:
            - nlp-net

networks:
    nlp-net:
        driver: "bridge"
