version: '3'

services:
    master:
        image: lachrimae/hadoop-master
        container_name: master
        expose: 
            - "20"
        ports:
            - "7077:7077"
        networks:
            - default
            - nlp-net
    slave:
        image: lachrimae/hadoop-slave
        container_name: slave
        expose:
            - "20"
        networks:
            - nlp-net

networks:
    nlp-net:
        driver: "bridge"
